spring:
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME:}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ${MAIL_PASSWORD:}
  datasource:
    password: ${MYSQL_PASSWORD:quyetthu}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:larente}?createDatabaseIfNotExist=true
server:
  port: ${port:8080}
